setwd("/Users/aryaviswanathan/Desktop/Data Science Specialization/Course 4 - Exploratory Data Analysis/Week 1")

all_data <- read.csv("household_power_consumption.txt",header=TRUE,sep=';',na.strings="?")
all_data$Date <- as.Date(all_data$Date,format="%d/%m/%Y")
data <- subset(x=all_data,subset=(Date>="2007-02-01" & Date<="2007-02-02"))
date_time <- paste(as.Date(data$Date), data$Time)
data$date_time <- as.POSIXct(date_time)
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(data$date_time,data$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(data$date_time,data$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(data$date_time,data$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(data$date_time,data$Sub_metering_2,type="l",col="red")
lines(data$date_time,data$Sub_metering_3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=1,bty="n")
plot(data$date_time,data$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()